#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

import apply_ayu_v03_fixed as fixed
import apply_ayu_edit_history as edit_history

base = fixed.base


def patch_read_state(text: str) -> str:
    """Suppress read receipts by consuming the Postbox sync operation, except
    for the one-shot read generated by Ayu's explicit send pulse.

    The old v0.2/v0.3 low-level shortcut completed synchronously while the
    PeerReadStateSynchronizationOperation was still visible. Telegram's
    ManagedSynchronizePeerReadStates completion handler immediately calls
    update() again, which could recurse until the thread hit its stack guard.
    """
    old = """func synchronizePeerReadState(network: Network, postbox: Postbox, stateManager: AccountStateManager, peerId: PeerId, push: Bool, validate: Bool) -> Signal<Never, PeerReadStateValidationError> {\n    var signal: Signal<Never, PeerReadStateValidationError> = .complete()\n    if push {\n        signal = signal\n        |> then(pushPeerReadState(network: network, postbox: postbox, stateManager: stateManager, peerId: peerId))\n    }\n    if validate {\n        signal = signal\n        |> then(validatePeerReadState(network: network, postbox: postbox, stateManager: stateManager, peerId: peerId))\n    }\n    return signal\n}"""

    new = """func synchronizePeerReadState(network: Network, postbox: Postbox, stateManager: AccountStateManager, peerId: PeerId, push: Bool, validate: Bool) -> Signal<Never, PeerReadStateValidationError> {\n    // AYU_IOS_PATCH_v0_3: Ghost read suppression must remove the Postbox\n    // synchronization operation before completing. Returning .single(readState)\n    // here/inside pushPeerReadState completes synchronously while the operation is\n    // still visible, and ManagedSynchronizePeerReadStates immediately calls update()\n    // again -> unbounded SwiftSignalKit recursion / stack overflow.\n    // A send pulse arms one one-shot exception for this exact peer, so sending a\n    // message can mark the current chat read just like AyuGram.\n    let ayuAllowSendRead = AyuRuntimeSettings.suppressReadMessages && AyuSendPulseState.consumeReadReceipt(peerId: peerId)\n    if AyuRuntimeSettings.suppressReadMessages && !ayuAllowSendRead {\n        return postbox.transaction { transaction -> Void in\n            transaction.confirmSynchronizedIncomingReadState(peerId)\n        }\n        |> castError(PeerReadStateValidationError.self)\n        |> ignoreValues\n    }\n\n    var signal: Signal<Never, PeerReadStateValidationError> = .complete()\n    if push {\n        signal = signal\n        |> then(pushPeerReadState(network: network, postbox: postbox, stateManager: stateManager, peerId: peerId))\n    }\n    if validate {\n        signal = signal\n        |> then(validatePeerReadState(network: network, postbox: postbox, stateManager: stateManager, peerId: peerId))\n    }\n    return signal\n}"""

    return base.replace_once(text, old, new, "read-crashfix-transaction")


def patch_online_pulse(text: str) -> str:
    anchor = "public func enqueueMessages(account: Account, peerId: PeerId, messages: [EnqueueMessage]) -> Signal<[MessageId?], NoError> {"
    if anchor not in text:
        base.die("enqueueMessages anchor missing")

    helper = r'''
// AYU_IOS_PATCH_v0_3: Ayu-style 200 ms online pulse when the user sends a message.
// Wait for Telegram to acknowledge online first, then keep the account online for
// 200 ms and explicitly restore offline. This prevents the old race where the
// offline request could overtake the online request on a slow connection.
private func ayuSendOnlinePulse(account: Account) {
    guard AyuRuntimeSettings.shouldPulseOnlineOnSend else {
        return
    }

    let online = account.network.request(Api.functions.account.updateStatus(offline: .boolFalse))
    |> `catch` { _ -> Signal<Api.Bool, NoError> in
        return .single(.boolFalse)
    }

    let _ = online.start(next: { _ in
        Queue.mainQueue().after(0.2) {
            guard AyuRuntimeSettings.suppressOnlineStatus else {
                return
            }
            let offline = account.network.request(Api.functions.account.updateStatus(offline: .boolTrue))
            |> `catch` { _ -> Signal<Api.Bool, NoError> in
                return .single(.boolFalse)
            }
            let _ = offline.start(next: { _ in
                AyuGhostLastSeen.recordNow()
            })
        }
    })
}

'''
    text = text.replace(anchor, helper + anchor, 1)
    text = base.replace_once(
        text,
        anchor + "\n    let signal:",
        anchor + "\n    ayuSendOnlinePulse(account: account)\n    let signal:",
        "enqueue-pulse-call",
    )

    transaction_anchor = """func enqueueMessages(transaction: Transaction, account: Account, peerId: PeerId, messages: [(Bool, EnqueueMessage)], disableAutoremove: Bool = false, transformGroupingKeysWithPeerId: Bool = false) -> [MessageId?] {\n    /**\n"""
    transaction_replacement = """func enqueueMessages(transaction: Transaction, account: Account, peerId: PeerId, messages: [(Bool, EnqueueMessage)], disableAutoremove: Bool = false, transformGroupingKeysWithPeerId: Bool = false) -> [MessageId?] {\n    // AYU_IOS_PATCH_v0_3: sending during the explicit online pulse also marks\n    // everything currently visible in this peer as read. When Ghost suppresses\n    // receipts, arm a one-shot server-sync exception for this peer only.\n    if AyuRuntimeSettings.shouldPulseOnlineOnSend {\n        if AyuRuntimeSettings.suppressReadMessages {\n            AyuSendPulseState.armReadReceipt(peerId: peerId)\n        }\n        let ayuReadNamespace: MessageId.Namespace\n        if peerId.namespace == Namespaces.Peer.SecretChat {\n            ayuReadNamespace = Namespaces.Message.SecretIncoming\n        } else {\n            ayuReadNamespace = Namespaces.Message.Cloud\n        }\n        if let index = transaction.getTopPeerMessageIndex(peerId: peerId, namespace: ayuReadNamespace) {\n            let _ = transaction.applyInteractiveReadMaxIndex(index)\n        }\n    }\n\n    /**\n"""
    return base.replace_once(text, transaction_anchor, transaction_replacement, "enqueue-read-on-send")


# Keep the corrected deleted-message patch from apply_ayu_v03_fixed.py, replace
# the old read suppression with the transaction-safe version, and replace the
# old fire-and-forget pulse with a sequenced pulse + read-on-send implementation.
base.patch_read_state = patch_read_state
base.patch_online_pulse = patch_online_pulse


if __name__ == "__main__":
    repo = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    repo = repo.expanduser().resolve()
    here = Path(__file__).resolve().parent
    base.install_payload(
        here / "payload" / "AyuSendPulseState.swift",
        repo / "submodules/TelegramCore/Sources/State/AyuSendPulseState.swift",
        "send-pulse state",
    )
    base.main()
    edit_history.apply(repo)
